// Single source of truth for roles and permissions on the client.
// firestore.rules / storage.rules embed the same presets (generated by
// scripts/generate-rules.mjs), so change permission-presets.json and re-run
// `npm run rules:generate` instead of editing either side by hand.
import presetData from "./permission-presets.json";

/** Permission key such as "leads.view" (see permission-presets.json). */
export type Permission = string;

export const PERMISSIONS = presetData.permissions as { key: Permission; group: string; label: string }[];
export const ALL_PERMISSIONS: Permission[] = PERMISSIONS.map((p) => p.key);
export const ROLE_OPTIONS = presetData.roles as { value: string; label: string }[];
export const SUPER_ROLES: string[] = presetData.superRoles;
const PRESETS = presetData.presets as Record<string, Permission[]>;

export function roleLabel(role: string | null | undefined) {
  return ROLE_OPTIONS.find((r) => r.value === role)?.label || role || "—";
}

export function isSuperRole(role: string | null | undefined) {
  return !!role && SUPER_ROLES.includes(role);
}

export function presetFor(role: string): Permission[] {
  if (isSuperRole(role)) return [...ALL_PERMISSIONS];
  return [...(PRESETS[role] || [])];
}

export interface PermissionSubject {
  role: string;
  permissions?: string[] | null;
  disabled?: boolean;
}

/** Explicit per-user permissions win; otherwise the role preset applies. */
export function effectivePermissions(r: PermissionSubject | null | undefined): Set<Permission> {
  if (!r || r.disabled) return new Set();
  if (isSuperRole(r.role)) return new Set(ALL_PERMISSIONS);
  const list = Array.isArray(r.permissions) ? r.permissions : presetFor(r.role);
  return new Set(list.filter((p): p is Permission => (ALL_PERMISSIONS as string[]).includes(p)));
}

export function canAny(perms: Set<Permission>, needed: Permission[]) {
  return needed.some((p) => perms.has(p));
}

/** Which permission unlocks each sidebar tab. */
export const TAB_PERMISSIONS: Record<string, Permission[]> = {
  dash: ["dashboard.view"],
  ai: ["dashboard.view", "reports.view", "finance.view", "leads.view", "schedule.view"],
  whatsapp: ["whatsapp.view"],
  leads: ["leads.view"],
  sales: ["leads.view", "leads.own"],
  products: ["products.view", "products.manage"],
  clients: ["clients.view"],
  projects: ["projects.view"],
  assignments: ["assignments.manage"],
  invoices: ["invoices.view"],
  accounting: ["finance.view"],
  khata: ["finance.view"],
  accounts: ["finance.view"],
  team: ["team.view"],
  schedule: ["schedule.view", "schedule.own"],
  reports: ["reports.view"],
  performance: ["performance.view"],
  budget: ["finance.view"],
  queries: ["queries.manage"],
  settings: ["settings.manage", "users.manage", "audit.view"],
  myportal: ["myportal.view"],
  history: ["history.manage"],
};

/**
 * Read / write access per workspace collection: any listed permission grants
 * access. firestore.rules is generated from the same JSON (leads have extra
 * hand-written rules there).
 */
export const COLLECTION_READ = presetData.collectionRead as Record<string, Permission[]>;
export const COLLECTION_WRITE = presetData.collectionWrite as Record<string, Permission[]>;

/**
 * Collections a My Portal user can still read, limited to documents whose
 * field (value here) equals their linked team record id (roleDoc.teamId).
 */
export const OWN_SCOPED = presetData.ownScoped as Record<string, string>;

/** Sales assistant: collections limited to their own documents (field = their team id). */
export const SALES_OWN_SCOPED = presetData.salesOwnScoped as Record<string, string>;
